### ISSUE TITLE
Sensor Problem 2022.4.1

### ISSUE THREAD

**Issue by DaHype** [barban-dev/homeassistant-midea-dehumidifier#55]
In New Version from Home Assistent 2022.4.1 one Sensor dont Work. With old Version before, No Problem.
Its Problem of the New Update?
Or any solution. Thanks
![Screenshot_20220408-204544_Home Assistant](https://user-images.githubusercontent.com/102579433/162503202-a478f436-cd05-4f4a-a9da-266f6840de11.jpg)
![Screenshot_20220408-204606_Home Assistant](https://user-images.githubusercontent.com/102579433/162503214-754af3b4-3025-4193-a23d-2446363bc398.jpg)
![Screenshot_20220408-204645_Home Assistant](https://user-images.githubusercontent.com/102579433/162503248-507a96c3-4dbf-495f-b6e3-8a6301e472fb.jpg)

**Comment by langerma** [comment]
same here

**Comment by DaHype** [comment]
Thanks. Hope it can be fixed soon from @barban-dev .

I reported already here:
https://github.com/home-assistant/core/issues/69727#issuecomment-1093788899

But it was closed  with " issue with a custom component,
 You need to bring this issue to that developer"

**Comment by sprocket7** [comment]
I also hope it will be fixed soon by the inventor.

**Comment by matteocorti** [comment]
Same here

**Comment by justinmtilley** [comment]
FYI - I manually applied the fixes in two of the outstanding Pull Requests and this problem was resolved.

Thanks to drthanwho & ankostis.

Likely fix for this problem (replace device_state_attributes with extra_state_attributes): 
https://github.com/barban-dev/homeassistant-midea-dehumidifier/pull/42

Cause of issue #35 at setup:
https://github.com/barban-dev/homeassistant-midea-dehumidifier/pull/53

Not ideal given the next update will overwrite your changes, but hopefully the next update contains the merge of these PR's.

**Comment by sprocket7** [comment]
https://github.com/barban-dev/homeassistant-midea-dehumidifier/issues/45#issuecomment-994129142

It's finally working

**Comment by ptgomes** [comment]
> FYI - I manually applied the fixes in two of the outstanding Pull Requests and this problem was resolved.
> 
> Thanks to drthanwho & ankostis.
> 
> Likely fix for this problem (replace device_state_attributes with extra_state_attributes): #42
> 
Where do you replace?
